# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
domain:              mseriukov.github.io
description:         ''
url:                 https://mseriukov.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mikhail Seriukov
  email:             mseriukov@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
